exclude_topics:
  [
    /rosout,
    (.*)/image_raw,
    /points_raw,
    /velodyne_(.*)_manager(.*),
    (.*)/velodyne_points
  ]

topics:
  [
    /decision_maker/state,
    /record_cmd
  ]

include_topics:
  [ /(.*) ]

#split : "duration=60"
split : "size=60"

compress: ""

max_splits: "11"


